#!/usr/bin/python3

import sys
from gmpy2 import mpz, is_prime

def factorize(n):
    factors = []
    
    while n > 1:
        d = 2
        while d <= n and not n % d == 0:
            d += 1
        factors.append(d)
        n //= d
        
    return factors

def main():
    if len(sys.argv) != 2:
        print("Usage: {} <file>".format(sys.argv[0]))
        sys.exit(1)
    
    input_file = sys.argv[1]
    
    with open(input_file, 'r') as f:
        for line in f:
            n = mpz(line.strip())
            factors = factorize(n)
            print("{}={}".format(n, "*".join(map(str, factors))))

if __name__ == "__main__":
    main()

